---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add MariaDB ubuntu bionic repository key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: '0xF1656F24C74CD1D8'

- name: Add MariaDB 10.4 ubuntu bionic repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64,arm64,ppc64el] http://mirrors.syringanetworks.net/mariadb/repo/10.4/ubuntu bionic main"
    state: present
  when: mariadb.version == "10.4"

- name: Install MariaDB Packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - mariadb-server
      - mariadb-client
      - python-mysqldb

- name: Ensure MariaDB service running
  become: yes
  service: name=mariadb state=started enabled=yes

- name: Set root user password
  become: yes
  # If .my.cnf already exists, this will cause an mysql-root-password update.
  mysql_user:
    name: root
    password: "{{ mariadb.root_password}}"
    host: "localhost"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create .my.cnf for vagrant
  become: yes
  template:
    src: "{{role_path}}/files/client.my.cnf.j2"
    dest: "{{ansible_env.HOME}}/.my.cnf"
    owner: vagrant
    group: vagrant
    mode: 0600

- name: Create .my.cnf for root
  become: yes
  template:
    src: "{{role_path}}/files/client.my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Create databases
  mysql_db: name={{ mariadb.database }} state=present login_user=root login_password={{ mariadb.root_password }}

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mariadb.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"

- name: Create users
  mysql_user:
    name: "{{ mariadb.user }}"
    password: "{{ mariadb.password }}"
    priv: "{{ mariadb.grants }}"
    login_user: root
    login_password: "{{ mariadb.root_password }}"
    state: present