---
- name: Install Doxygen and required packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - doxygen
      - flex
      - bison
      - make
      - cmake
      - graphviz
      - build-essential
